CREATE OR REPLACE FUNCTION is_odd_fast(val INT) RETURNS BOOLEAN AS 'MODULE_PATHNAME', 'is_odd_fast' LANGUAGE C STRICT;
CREATE OR REPLACE FUNCTION is_odd_slow(val INT) RETURNS BOOLEAN AS 'MODULE_PATHNAME', 'is_odd_slow' LANGUAGE C STRICT;
