CREATE OR REPLACE FUNCTION is_odd_fast(val INT) RETURNS BOOLEAN AS 'MODULE_PATHNAME', 'is_odd_fast' LANGUAGE C STRICT;
CREATE OR REPLACE FUNCTION is_odd_slow(val INT) RETURNS BOOLEAN AS 'MODULE_PATHNAME', 'is_odd_slow' LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION _int32_sum_trans_fn(state BIGINT,
   val INT) RETURNS BIGINT
   AS 'MODULE_PATHNAME', 'int32_sum_trans'
   LANGUAGE C IMMUTABLE;

CREATE OR REPLACE AGGREGATE mysum(INT)
(
    sfunc = _int32_sum_trans_fn,
    stype = BIGINT
);